name: Publish builder images to Docker Hub

on:
  workflow_dispatch:

env:
  DH_USER: mrzelee

jobs:
  yugabyte-builder-arm64:
    name: Build and Push ARM64 Image
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/images/yugabyte/Dockerfile.builder
          platforms: linux/arm64
          push: true
          tags: ${{ env.DH_USER }}/yugabyte-builder:arm64-latest
          build-args: |
            BASE_IMAGE=docker.io/library/almalinux:8@sha256:16b6f4a8e88d1a27cafaac681ff78613c24033028fbcb3459427c91fb01937d6

  yugabyte-builder-amd64:
    name: Build and Push AMD64 Image
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/images/yugabyte/Dockerfile.builder
          platforms: linux/amd64
          push: true
          tags: ${{ env.DH_USER }}/yugabyte-builder:amd64-latest
          build-args: |
            BASE_IMAGE=docker.io/library/almalinux:8

  create-manifest:
    name: Create and Push Multi-Platform Manifest
    runs-on: ubuntu-latest
    needs: [yugabyte-builder-arm64, yugabyte-builder-amd64]
    steps:
      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest list
        run: |
          docker manifest create ${{ env.DH_USER }}/yugabyte-builder:latest \
            --amend ${{ env.DH_USER }}/yugabyte-builder:amd64-latest \
            --amend ${{ env.DH_USER }}/yugabyte-builder:arm64-latest

          docker manifest push ${{ env.DH_USER }}/yugabyte-builder:latest

